import { DOMAIN } from "./services";

export interface Project {
  slug: string;
  title: string;
  category: string;
  location: string;
  image: string;
  images: string[];
  description: string;
  longDescription: string;
  tags: string[];
  serviceSlug: string;
  metaTitle: string;
  metaDescription: string;
}

export const PROJECTS: Project[] = [
  {
    slug: "external-property-maintenance-and-repairs",
    title: "External Property Maintenance and Repairs",
    category: "Refurbishments and Conversions",
    location: "Folkestone, Kent",
    image: "/images/adelphi-court/new external property refurbishment and restoration service in canterbury.jpg",
    images: [],
    description: "16-week external refurbishment of Adelphi Court, a Victorian hotel converted into apartments in the 1960s, located at 2 Augusta Gardens, Folkestone.",
    longDescription: "In 2024, our team completed a 16-week external refurbishment of Adelphi Court, a Victorian hotel converted into apartments in the 1960s, located at 2 Augusta Gardens, Folkestone. Situated near the seafront, the building had deteriorated due to 12 years without maintenance, missing its typical 5-6 year cycle.\n\nThe project required full scaffolding to address issues from the roof down. We repaired the roof and valleys, stitched structural cracks, and restored rotted sliding sash windows. Wrought iron balconies were refurbished, surfaces stabilized, and the exterior fully redecorated. Perimeter brick walls were repaired and partially rebuilt, concrete pathways fixed, and glass replaced. Rainwater goods and flat roof membranes were maintained, drains jetted, new signage installed, and rendering applied.\n\nThe refurbishment revitalized Adelphi Court, enhancing its durability and preserving its historic charm against Folkestone's harsh coastal elements.",
    tags: ["16 weeks", "Property Restoration", "External Refurbishment", "Victorian Building"],
    serviceSlug: "property-refurbishment",
    metaTitle: "External Property Maintenance and Repairs in Folkestone | Superstructure Services",
    metaDescription: "16-week external refurbishment of Victorian Adelphi Court in Folkestone, Kent. Full scaffolding, roof repairs, window restoration by Superstructure Services.",
  },
  {
    slug: "electrician-rewiring-service-canterbury",
    title: "Full Electrical Re-Wiring",
    category: "Electrical works",
    location: "Kent",
    image: "/images/electrical-rewire/full re-wiring electrician in canterbury.jpg",
    images: [
      "/images/electrical-rewire/full re-wiring electrician in canterbury.jpg",
      "/images/electrical-rewire/electrical contractor in canterbury kent.jpg",
      "/images/electrical-rewire/local electrician in canterbury, kent post codes.jpg",
      "/images/electrical-rewire/new fuse and EICR electrical specialist canterbury.jpg",
    ],
    description: "Full rewire of a three-bedroom end-of-terrace house at Lady Wootton's Green, Canterbury, replacing outdated circuits with modern wiring to meet UK safety standards.",
    longDescription: "At Lady Wootton's Green, Canterbury, our team revitalized the electrical system of a three-bedroom end-of-terrace house for Mrs. Neiwerth. We completed a full rewire, replacing outdated circuits with modern wiring to meet UK safety standards. A new consumer unit with advanced circuit breakers and RCDs was installed, ensuring safety and efficiency. This upgrade provided a reliable power infrastructure for the family's home, seamlessly integrated with the broader renovation, enhancing functionality in Canterbury, Kent.",
    tags: ["Over 4 weeks", "Full Rewire", "Consumer Unit", "UK Safety Standards", "Lady Wootton's Green"],
    serviceSlug: "electrician-canterbury",
    metaTitle: "Full Electrical Rewiring in Canterbury | Superstructure Services",
    metaDescription: "Full electrical rewire at Lady Wootton's Green, Canterbury. New consumer unit, modern wiring to UK safety standards. Superstructure Services.",
  },
  {
    slug: "bathroom-installation-canterbury-plumber",
    title: "New Bathroom and Plumbing Maintenance",
    category: "Plumbing and Drainage",
    location: "Canterbury",
    image: "/images/bathroom-adelphi/new bathroom installation canterbury.jpg",
    images: [
      "/images/bathroom-adelphi/new bathroom installation canterbury.jpg",
      "/images/bathroom-adelphi/bathroom appliance plumber canterbury.jpg",
      "/images/bathroom-adelphi/canterbury plumbing service.jpg",
      "/images/new-bathroom/bathroom-installation-canterbury.jpg",
      "/images/new-bathroom/bathrooms-canterbury.jpg",
      "/images/new-bathroom/bathrooms-in-canterbury-kent.jpg",
      "/images/new-bathroom/bathrooms-in-canterbury.jpg",
      "/images/new-bathroom/bathroom-renovation-service-kent.jpg",
      "/images/new-bathroom/new-bathroom-installation-near-me-kent.jpg",
      "/images/new-bathroom/new-bathroom-kent-installation.jpg",
      "/images/new-bathroom/new-shower-installation-service-canterbury-kent.jpg",
      "/images/new-bathroom/bathroom-design-and-installation-canterbury.jpg",
      "/images/new-bathroom/bathroom-fitters-canterbury.jpg",
      "/images/new-bathroom/bathroom-fitters-kent.jpg",
      "/images/new-bathroom/bathroom-plumbing-experts-in-canterbury.jpg",
      "/images/new-bathroom/bathroom-renovation-canterbury.jpg",
      "/images/new-bathroom/bathroom-renovation-kent.jpg",
      "/images/new-bathroom/bathroom-renovation-specialists-in-canterbury-and-kent-post-codes.jpg",
      "/images/new-bathroom/bathroom-tiling-and-tiler-in-canterbury-and-kent.jpg",
      "/images/new-bathroom/builder-for-bathrooms-near-me-in-kent-and-canterbury.jpg",
      "/images/new-bathroom/classic-modern-bathroom-refurbishment-service-canterbury.jpg",
      "/images/new-bathroom/design,-supply-and-fit-out-new-bathrooms-kent.jpg",
      "/images/new-bathroom/new-bath-tub-canterbury-and-kent-installation.jpg",
      "/images/new-bathroom/new-bathroom-fitter-canterbury.jpg",
      "/images/new-bathroom/new-toilet,-towel-rail-refurb-kent.jpg",
      "/images/new-bathroom/rainfall-shower-installation-canterbury-kent.jpg",
      "/images/new-bathroom/sinks,-showers,-lighting-new-bath-installation.jpg",
      "/images/new-bathroom/wet-room-and-shower-installers-in-canterbury.jpg",
    ],
    description: "Comprehensive plumbing and bathroom transformation at Lady Wootton's Green, Canterbury, modernizing facilities for a three-bedroom end-of-terrace house.",
    longDescription: "At Lady Wootton's Green in Canterbury, our team transformed the plumbing and bathroom facilities of a three-bedroom end-of-terrace house for Mrs. Neiwerth. Tasked with modernizing the property for her family's use, we executed a comprehensive overhaul of the plumbing systems, delivering a functional and elegant bathroom and WC.\n\nWe stripped out the outdated bathroom and associated pipework, replacing them with a bespoke, modern bathroom and WC designed to blend style with practicality. Our skilled plumbers installed new, high-quality fixtures and fittings, ensuring efficient drainage and reliable performance. Additionally, we fitted a state-of-the-art condensing boiler in the loft, with venting integrated through the roof, to enhance the home's heating and water systems. This meticulous work ensured long-term durability and aligned with the family's vision for a comfortable, sustainable home in Canterbury, Kent.",
    tags: ["4 weeks", "Bathroom Installation", "Condensing Boiler", "Plumbing Overhaul", "Lady Wootton's Green"],
    serviceSlug: "new-bathroom-fitter-canterbury",
    metaTitle: "New Bathroom Installation in Canterbury | Superstructure Services",
    metaDescription: "Bathroom and plumbing transformation at Lady Wootton's Green, Canterbury. Modern fixtures, condensing boiler installation by Superstructure Services.",
  },
  {
    slug: "property-maintenance-canterbury",
    title: "Full Property Refurbishment & Maintenance",
    category: "Refurbishments and Conversions",
    location: "Lady Woottens Green, Canterbury, Kent",
    image: "/images/refurb-adelphi/builder in canterbury, local quality.jpg",
    images: [
      "/images/refurb-new/domestic refurb in kent builder.JPG",
      "/images/refurb-new/full refurbishment experts near me in canterbury.jpg",
      "/images/refurb-new/House builder in Kent.JPG",
      "/images/refurb-new/internal property refurbs builder kent post codes.jpg",
      "/images/refurb-new/Property maintanence in Canterbury Kent.JPG",
      "/images/refurb-new/Property renovation service in Canterbury Kent.JPG",
      "/images/refurb-new/Refurbishment in Canterbury.JPG",
      "/images/refurb-new/Refurbishment property experts in kent england.jpg",
      "/images/refurb-new/Renovation in Canterbury Kent.JPG",
      "/images/refurb-new/renovations-refurbishments-builder-canterbury-kent.JPG",
    ],
    description: "Complete renovation of a three-bedroom end-of-terrace house at Lady Wootton's Green, Canterbury for Mrs. Neiwerth - full strip-out, rewiring, new boiler, bespoke kitchen, bathroom, and full redecoration.",
    longDescription: "In the heart of Canterbury, at Lady Wootton's Green, our team had the privilege of transforming a three-bedroom end-of-terrace house into a stunning, functional, and elegant home for Mrs. Neiwerth and her family. Purchased as a residence for her mature children attending education in Canterbury and a welcoming retreat for Mr. and Mrs. Neiwerth visiting from Sussex, this property required an extensive renovation to meet their vision. Guided by Mrs. Neiwerth's exquisite design aesthetics, we delivered a comprehensive overhaul that blended modern craftsmanship with timeless charm, resulting in a home that radiates sophistication and comfort.\n\nThe project demanded a complete strip-out of the existing interiors, including furniture, fixings, kitchen, bathrooms, electrical systems, and the boiler. The scope also extended to minor roofing repairs and the installation of two Velux windows to enhance natural light. Our skilled carpenters, electricians, and plumbers worked diligently to address every aspect of the property, ensuring a seamless transformation from foundation to finish.\n\nFull Electrical Rewiring: We completed a full rewire of the property, ensuring a safe and modern electrical system compliant with current standards, tailored to the family's needs for both daily living and long-term reliability.\n\nNew Condensing Boiler Installation: A state-of-the-art condensing boiler was expertly installed in the loft, with venting seamlessly integrated through the roof, improving energy efficiency and heating performance.\n\nBespoke Bathroom and WC: Our team crafted a luxurious new bathroom and WC, complete with modern pipework, fixtures, and fittings, designed for both functionality and aesthetic appeal.\n\nHandmade Kitchen and Utility Room: We designed and installed a bespoke kitchen and utility room, incorporating Mrs. Neiwerth's preference for a shabby-chic style. The handcrafted cabinetry, worktops, and detailing added warmth and character to the heart of the home.\n\nRoofing and Velux Windows: The roof underwent necessary repairs, and we installed two Velux windows to flood the interior with natural light, enhancing the spacious and airy feel of the home.\n\nCustom Hardwood French Doors: Our carpenters crafted a stunning set of handmade hardwood French doors with a matching surround, opening to the courtyard and creating a seamless indoor-outdoor connection.\n\nParquet Flooring Restoration: The original parquet flooring on the ground floor was meticulously sanded and refinished, restoring its natural beauty and adding a touch of heritage to the modernized space.\n\nComplete Redecoration: The entire property was redecorated with high-quality finishes, including designer wallcoverings, to reflect Mrs. Neiwerth's sophisticated taste and elevate the home's ambiance.\n\nSisal Carpets and Stair Runner: We fitted luxurious sisal carpets and a custom-edged stair runner, adding texture and elegance to the interiors.\n\nExternal Overhaul: The exterior of the property was revitalized, ensuring a polished and cohesive appearance that complemented the internal upgrades.\n\nGarden Landscaping: Following the main renovation, we returned to landscape the garden, creating a serene outdoor space for the family to enjoy during their stays in Canterbury.\n\nThis project exemplified our commitment to excellence, blending our expertise in carpentry, electrical rewiring, plumbing, and property maintenance to deliver a home that exceeded expectations. The collaboration with Mrs. Neiwerth allowed us to bring her vision to life, combining sustainable materials, bespoke craftsmanship, and innovative solutions to create a space that is both practical for her children's educational needs and a welcoming haven for family visits in the beautiful city of Canterbury.\n\nThe end result was a breathtaking transformation that not only enhanced the property's functionality but also elevated its aesthetic appeal, making it a standout residence in Lady Wootton's Green.\n\nOur team takes pride in having delivered a project that reflects the enduring quality and precision that define our carpentry and property maintenance services in Canterbury, Kent.",
    tags: ["Over 4 weeks", "Refurbishment", "Carpentry", "Maintenance"],
    serviceSlug: "property-refurbishment",
    metaTitle: "Full Property Refurbishment in Canterbury | Superstructure Services",
    metaDescription: "Complete renovation at Lady Wootton's Green, Canterbury. Bespoke kitchen, rewiring, new boiler, parquet restoration by Superstructure Services.",
  },
  {
    slug: "carpentry-hardwood-decking",
    title: "Carpentry & Hardwood Decking",
    category: "Carpentry",
    location: "Hothfield near Ashford, Kent",
    image: "/images/carpentry-decking-adelphi/canterbury patio and decking service.jpg",
    images: [
      "/images/carpentry-decking-adelphi/canterbury patio and decking service.jpg",
      "/images/carpentry-decking-adelphi/canterbury decking and restoration experts.jpg",
      "/images/carpentry-decking-adelphi/canterbury-bespoke-garden-decking.jpg.jpg",
    ],
    description: "Complete renewal and redesign of degraded front entrance decking for Dr. Dunnet's large detached home in Hothfield, using Balau hardwood.",
    longDescription: "The project involved a large, extended detached home set on several acres, featuring a prominent front entrance decking area built into sloping ground. The renovation focused on the complete renewal and redesign of the degraded front entrance decking. Dr. Dunnet, the homeowner, commissioned the project to replace the deteriorating structure with a durable, aesthetically enhanced design.\n\nThe renovation addressed the degraded decking through a comprehensive rebuild, incorporating high-quality materials and preservation techniques. The completed works included complete removal of the existing decking structure, which was integrated into the sloping terrain. Construction of a new timber framework using tanalised timber for enhanced durability. Application of preservative soak to the timber and bitumen coating on top surfaces to maximize the structure's longevity. Installation of Balau hardwood decking for the flooring, steps, and wall structure, which included integrated storage and cladding for the large supporting posts. Addition of Balau hardwood handrails between the posts to complete the design, ensuring both safety and aesthetic cohesion.\n\nThe project delivered a robust, long-lasting front entrance decking area that enhanced the property's functionality and visual appeal while seamlessly integrating with the surrounding landscape.",
    tags: ["4 weeks", "Balau Hardwood", "Tanalised Timber", "External Refurbishment", "Decking"],
    serviceSlug: "carpenter-in-canterbury",
    metaTitle: "Hardwood Decking in Hothfield, Ashford | Superstructure Services",
    metaDescription: "Balau hardwood decking installation in Hothfield near Ashford. Complete front entrance renewal with tanalised timber framework.",
  },
  {
    slug: "listed-building-refurb-canterbury",
    title: "Listed Building Restoration & Kitchen Installation",
    category: "Listed Building Restoration",
    location: "Mersham, Ashford, Kent",
    image: "/images/listed-building-adelphi/canterbury-listed-building-refurbishment.jpg.jpg",
    images: [
      "/images/listed-building-new/BESPOK~1.JPG",
      "/images/listed-building-new/canterbury-bespoke-kitchen-fittings.jpg.jpg",
      "/images/listed-building-new/canterbury-custom-kitchen-joinery.jpg.jpg",
      "/images/listed-building-new/canterbury-custom-kitchen-worktops.jpg.jpg",
      "/images/listed-building-new/canterbury-heritage-carpentry-restoration.jpg.jpg",
      "/images/listed-building-new/canterbury-listed-building-refurbishment.jpg.jpg",
      "/images/listed-building-new/kent-custom-kitchen-cabinets.jpg.jpg",
      "/images/listed-building-new/kent-heritage-kitchen-restoration.jpg.jpg",
      "/images/listed-building-new/kent-historic-property-refurbishment.jpg.jpg",
      "/images/listed-building-new/kent-listed-building-joinery.jpg.jpg",
    ],
    description: "Complete overhaul of a 40-year-old kitchen in a Grade II listed 16th-century building on Burgate, with knock-through, full rewiring and re-plumbing.",
    longDescription: "The project centered on a large, Grade II listed 16th-century building on Burgate, a historically significant property subject to strict preservation regulations. The renovation involved the complete overhaul of a 40-year-old kitchen, including a knock-through to reconfigure the space, full rewiring, and re-plumbing. The objective was to deliver a modern, high-end, fully functional kitchen while adhering to listed building regulations.\n\nA structural survey was conducted to assess the feasibility of wall removal while ensuring compliance with heritage requirements. The renovation encompassed demolition and removal of outdated kitchen fittings, faux beams, floor finishes, old electrical cabling, and pipework. Structural modifications, including a wall knock-through, with reinforcements to meet listed building standards. Complete rewiring of the kitchen to current electrical standards, accompanied by certification. Full re-plumbing to support the new kitchen layout and appliances, with certification. Installation of high-end kitchen fittings, fixtures, and finishes, creating a modern, efficient space that harmonized with the property's historical character.\n\nThe project was completed with full adherence to Grade II listed building regulations, preserving the property's heritage while delivering a premium, fully certified kitchen.",
    tags: ["4 weeks", "Grade II Listed", "16th Century", "Kitchen Installation", "Listed Building Regulations"],
    serviceSlug: "listed-building-restoration",
    metaTitle: "Listed Building Kitchen in Mersham, Ashford | Superstructure Services",
    metaDescription: "Grade II listed 16th-century building kitchen renovation in Mersham. Full compliance with heritage regulations by Superstructure Services.",
  },
  {
    slug: "roof-repair-canterbury",
    title: "External Refurbishment and Roof Repair",
    category: "Roofing",
    location: "Deal High Street, Kent",
    image: "/images/roof-repair-adelphi/canterbury-bespoke-roofing-joinery.jpg.jpg",
    images: [
      "/images/roof-repair-adelphi/canterbury-bespoke-roofing-joinery.jpg.jpg",
      "/images/roof-repair-adelphi/Complete roof replacement service deal, canterbury, kent.jpg",
      "/images/roof-repair-adelphi/Roofer in canterbury.jpg",
      "/images/roof-repair-adelphi/Roofing service and specialists in kent post codes.jpg",
      "/images/roof-repair-adelphi/canterbury-structural-roofing-carpentry.jpg.jpg",
      "/images/roof-repair-adelphi/external roof chimney repair service canterbury, kent.jpg",
      "/images/roof-repair-adelphi/kent-chimney-flashing-carpentry.jpg.jpg",
      "/images/roof-repair-adelphi/new chimney replacement service canterbury.jpg",
      "/images/roof-repair-adelphi/new roof installation service canterbury.jpg",
      "/images/roof-repair-adelphi/roof repair near me canterbury kent.jpg",
      "/images/roof-repair-adelphi/roof repair service in canterbury, kent.jpg",
    ],
    description: "Emergency repair and comprehensive refurbishment of a high street shop with first-floor flat after HGV collision damage, including complete roof replacement.",
    longDescription: "The property consisted of a high street shop with a first-floor flat and an adjacent terraced house, part of a family business portfolio of historic buildings leased or rented across the country. A heavy goods vehicle (HGV) struck the shop front, causing structural damage. Dover District Council mandated immediate action to secure the area. After ensuring safety, I met with the client, a long-term partner, to conduct a comprehensive survey of the property before initiating repairs.\n\nBeyond the damaged shop front, the survey revealed several critical issues: The roof was at the end of its lifespan and required replacement. The chimney was unstable, posing a safety risk. Coping stones on the parapet walls were deteriorated. Render and joinery repairs were needed to restore structural integrity. The property required a complete redecoration. Installation of new deep-flow guttering and downpipes was necessary. Insulation upgrades were recommended for the roof space and mansard to improve energy efficiency.\n\nPermits and permissions for scaffolding and other necessary works had been secured from Dover District Council. Repair and restoration work commenced promptly, addressing both the immediate damage and the broader maintenance needs ensuring the property's longevity and compliance with safety standards.",
    tags: ["8 weeks", "Emergency Repair", "Roof Replacement", "Chimney Repair", "Shop External Repair"],
    serviceSlug: "new-roof-installation-repairs",
    metaTitle: "External Refurbishment & Roof Repair in Deal | Superstructure Services",
    metaDescription: "Emergency shop repair and roof replacement in Deal High Street. HGV damage restoration, chimney repair by Superstructure Services.",
  },
  {
    slug: "entrance-restoration-canterbury",
    title: "Entrance Restoration in Canterbury",
    category: "Carpentry",
    location: "Hothfield near Ashford",
    image: "/images/entrance-restoration-adelphi/best local carpenter in canterbury, full works.jpg",
    images: [
      "/images/entrance-restoration-adelphi/best local carpenter in canterbury, full works.jpg",
      "/images/entrance-restoration-adelphi/Carpentry Restoration works, carpenter in canterbury kent.jpg",
      "/images/entrance-restoration-adelphi/bespoke carpenter in canterbury service.jpg",
      "/images/entrance-restoration-adelphi/canterbury woodworker and quality carpenter.jpg",
      "/images/entrance-restoration-adelphi/canterbury-bespoke carpentry.jpg.jpg",
      "/images/entrance-restoration-adelphi/canterbury-carpentry-services.jpg.jpg",
      "/images/entrance-restoration-adelphi/canterbury-first-fix-carpentry.jpg.jpg",
      "/images/entrance-restoration-adelphi/canterbury-structural-carpentry.jpg.jpg",
      "/images/entrance-restoration-adelphi/canterbury-timber-framing.jpg.jpg",
      "/images/entrance-restoration-adelphi/joiner service in canterbury kent.jpg",
      "/images/entrance-restoration-adelphi/kent-bespoke-joinery-installations.jpg.jpg",
      "/images/entrance-restoration-adelphi/kent-second-fix-carpentry.jpg.jpg",
    ],
    description: "Restoration of a hand-built, two-storey green oak entrance structure that had settled over time, addressing water ingress and weathering.",
    longDescription: "The renovation focused on a large, extended detached home set on several acres, featuring a hand-built, two-storey green oak entrance structure that had settled over time. The structure required an overhaul to refresh its appearance and address water ingress caused by timber shrinkage. Scaffolding was erected to facilitate the work. Glazing beads were removed, large double-glazed units were sealed, and the beads were reinstalled. The entire structure underwent heavy abrasion to eliminate weathering. Joints, splits, and shakes in the timber were sealed using Repair Care Dry Flex, a two-component epoxy resin. The structure was finished with Sikkens HLS base coats and Sikkens Cetol Filter 7 top coats, restoring its aesthetic appeal and ensuring long-term protection against the elements.\n\nThe completed project revitalized the entrance, enhancing its durability and visual charm while preserving the property's distinctive character.",
    tags: ["1 week", "Green Oak", "Timber Restoration", "Epoxy Resin", "Sikkens Coating"],
    serviceSlug: "carpenter-in-canterbury",
    metaTitle: "Green Oak Entrance Restoration in Hothfield | Superstructure Services",
    metaDescription: "Green oak entrance structure restoration in Hothfield near Ashford. Timber sealing, Sikkens coating by Superstructure Services.",
  },
  {
    slug: "library-renovation-ashford",
    title: "Library Renovation",
    category: "Refurbishments and Conversions",
    location: "Hothfield, Ashford",
    image: "/images/library-renovation-adelphi/Property Renovation in Hothfield Ashford.JPG",
    images: [
      "/images/library-renovation-adelphi/Property Renovation in Hothfield Ashford.JPG",
      "/images/library-renovation-adelphi/Finish Project Renovation in Ashford.jpg",
      "/images/library-renovation-adelphi/Flooring and Dampproofing in Ashford.JPG",
      "/images/library-renovation-adelphi/Full property works and renovation in Ashford.JPG",
      "/images/library-renovation-adelphi/Library Refurbishment Ashford.JPG",
      "/images/library-renovation-adelphi/Property Renovation Ashford.JPG",
      "/images/library-renovation-adelphi/Property renovation in Ashford.JPG",
      "/images/library-renovation-adelphi/Property renovation works in Ashford.JPG",
    ],
    description: "Conversion of a large sitting room into a library for Mr and Mrs Dunnet in Hothfield, addressing floor movement and dampness issues.",
    longDescription: "We received an enquiry from a Mr and Mrs Dunnet who own a beautiful property in Hothfield, Kent, set in several acres of established gardens and recreation areas. The issues were explained regarding a large sitting room which required converting into a library. The issues explained were movement in the floor and general dampness to this and the surrounding wall areas.\n\nOn surveying the area, it was found that the floor plates were rotten and the damp course had broken down, mainly being due to the age of the building. Investigative works and trial pits were carried out to determine the footings. This would help us assess which type of sub floor to install.\n\nComplete removal of existing floor structure. Membrane, two layers of insulation, further membrane and then screeding was carried out. Rising damp resulted in hacking of the render internally and locally externally. A chemical damp course was then injected. Internally the walls were salt neutralised, two coats of tanking solution, plastering sand a cement render was applied with water proofing agent added, finally the room including a newly installed fire check ceiling was completely plastered.\n\nAs Mr and Mrs Dunnet had different plans for the room layout, it was re-wired and the plumbing altered to suit their needs. A new oak floor was installed along with oak skirting boards, bespoke oak door and frame.",
    tags: ["3 months", "Damp Course", "Floor Replacement", "Oak Flooring", "Complete Renovation"],
    serviceSlug: "property-refurbishment",
    metaTitle: "Library Renovation in Hothfield, Ashford | Superstructure Services",
    metaDescription: "Library conversion in Hothfield. Damp course treatment, oak flooring, complete room renovation by Superstructure Services.",
  },
  {
    slug: "home-office-creation-in-canterbury",
    title: "Home Office Creation",
    category: "Home Office",
    location: "Canterbury",
    image: "/images/home-office-adelphi/Home office installation in Canterbury.jpg",
    images: [
      "/images/home-office-adelphi/Home office installation in Canterbury.jpg",
      "/images/home-office-adelphi/Home Office Creation in Canterbury.jpg",
      "/images/home-office-adelphi/Home Office Installation in Canterbury Kent.jpg",
      "/images/home-office-adelphi/Home Office Set up in Canterbury, Kent.jpg",
      "/images/home-office-adelphi/Home office creation Canterbury Kent.jpg",
    ],
    description: "Conversion of part of a large living area into a workable office installation due to Covid restrictions, including custom computer setup.",
    longDescription: "Our Client in Canterbury, Kent required a workable office installation to their property due to Covid restrictions. We converted part of a large living area in his home and sectioned of an area, forming a new room. Electrical works, carpentry, plastering and painting to create a new space. Finally our connections designed a custom computer for them, exceeding their current work systems. We also had their computer set up for them and demonstrated after all of their data had been transferred.",
    tags: ["2 weeks", "Covid Conversion", "Custom Computer", "Room Partition", "Home Office Installation"],
    serviceSlug: "office-conversion",
    metaTitle: "Home Office Creation in Canterbury | Superstructure Services",
    metaDescription: "Home office conversion in Canterbury during Covid. Room partition, electrical works, custom computer setup by Superstructure Services.",
  },
  {
    slug: "domestic-refurbishment-in-canterbury",
    title: "Domestic Refurbishment",
    category: "Refurbishments and Conversions",
    location: "Mayfair, London",
    image: "/images/refurbishment-adelphi/Renovation in Canterbury Kent.JPG",
    images: [
      "/images/refurbishment-adelphi/Renovation in Canterbury Kent.JPG",
      "/images/refurbishment-adelphi/House builder in Kent.JPG",
      "/images/refurbishment-adelphi/Property maintanence in Canterbury Kent.JPG",
      "/images/refurbishment-adelphi/Property renovation service in Canterbury Kent.JPG",
      "/images/refurbishment-adelphi/Refurbishment in Canterbury.JPG",
      "/images/refurbishment-adelphi/domestic refurb in kent builder.JPG",
      "/images/refurbishment-adelphi/renovations-refurbishments-builder-canterbury-kent.JPG",
    ],
    description: "Full refurbishment of a large four-bedroom, four-bathroom flat in Mayfair, London, including new bathrooms, kitchen, boiler and partial rewire.",
    longDescription: "Our Client in London required a full refurbishment to their Large Flat in Mayfair. It was four bedrooms and four bathrooms with a large balconied lounge area. We installed new bathrooms, kitchen, boiler and a partial rewire. The project was completed on time and within budget.",
    tags: ["8 weeks", "Mayfair Flat", "Four Bedrooms", "Refurbishment All Trades", "London"],
    serviceSlug: "property-refurbishment",
    metaTitle: "Domestic Refurbishment in Mayfair, London | Superstructure Services",
    metaDescription: "Complete four-bedroom flat refurbishment in Mayfair. New bathrooms, kitchen, boiler by Superstructure Services.",
  },
  {
    slug: "underfloor-heating-in-canterbury",
    title: "Underfloor Heating Installation",
    category: "Underfloor heating",
    location: "Canterbury",
    image: "/images/underfloor-heating-adelphi/underfloor heating installation in kent and villages.JPG",
    images: [
      "/images/underfloor-heating-adelphi/underfloor heating installation in kent and villages.JPG",
      "/images/underfloor-heating-adelphi/Best underfloor heating in Canterbury Kent.jpg",
      "/images/underfloor-heating-adelphi/Full underfloor water heating Canterbury Kent.JPG",
      "/images/underfloor-heating-adelphi/Underfloor heating installer in Canterbury Kent.jpg",
      "/images/underfloor-heating-adelphi/Underfloor heating professional in Canterbury.jpg",
      "/images/underfloor-heating-adelphi/Underfloor heating service Canterbury.JPG",
    ],
    description: "Ultra modern retro-fitting of underfloor heating into screed using dust-free milling technique, avoiding excavation costs and upheaval.",
    longDescription: "Our client in Canterbury really wanted underfloor heating to the ground floor of their property but they did not want the upheaval or costs involved with excavating the entire ground floor up to a depth of 300mm. We advised on an ultra modern form of retro fitting underfloor heating into the screed. The screed is milled out in a completely dust free manner. Underfloor heating pipes installed into controllable zones at a fraction of the cost of conventional methods.",
    tags: ["1 week", "Retro-fit UFH", "Milled Screed", "Dust Free", "Controllable Zones"],
    serviceSlug: "underfloor-heating-installation",
    metaTitle: "Underfloor Heating Installation in Canterbury | Superstructure Services",
    metaDescription: "Retro-fit underfloor heating in Canterbury. Dust-free milled screed technique, controllable zones. Superstructure Services, Kent.",
  },
  {
    slug: "plumbing-and-drainage-in-canterbury",
    title: "New Bathroom, Plumbing and Drainage",
    category: "Plumbing and Drainage",
    location: "Canterbury",
    image: "/images/plumbing-bathroom-adelphi/Bathrooms in Canterbury Kent.jpg",
    images: [
      "/images/plumbing-bathroom-adelphi/Bathrooms in Canterbury Kent.jpg",
      "/images/plumbing-bathroom-adelphi/Bath installation in Canterbury Kent.JPG",
      "/images/plumbing-bathroom-adelphi/Bathroom installation in Kent.JPG",
      "/images/plumbing-bathroom-adelphi/Full plumbing works for Bathroom.JPG",
      "/images/plumbing-bathroom-adelphi/Plumbing in Canterbury.jpg",
      "/images/plumbing-bathroom-adelphi/Shower installation in Canterbury Kent.JPG",
      "/images/plumbing-bathroom-adelphi/Unit installation in Canterbury Kent.JPG",
      "/images/plumbing-bathroom-adelphi/bathroom fitter canterbury kent.JPG",
    ],
    description: "Complete update and change of layout to an old bathroom in Canterbury, delivering a modern feel.",
    longDescription: "Our client in Canterbury required a complete update and change of layout to their old bathroom. They loved the new modern feel that we supplied.",
    tags: ["1 week", "Bathroom Update", "Layout Change", "Plumbing", "Plastering", "Carpentry"],
    serviceSlug: "plumber-in-canterbury",
    metaTitle: "New Bathroom & Plumbing in Canterbury | Superstructure Services",
    metaDescription: "Complete bathroom update and layout change in Canterbury. Modern bathroom installation by Superstructure Services.",
  },
  {
    slug: "commercial-refurbishment-in-canterbury",
    title: "Commercial Refurbishment",
    category: "Refurbishments and Conversions",
    location: "London",
    image: "/images/commercial-adelphi/Commercial Refurbishment service in canterbury and kent.JPG",
    images: [
      "/images/commercial-adelphi/Commercial Refurbishment service in canterbury and kent.JPG",
      "/images/commercial-adelphi/Commercial-builder-in-Canterbury-Kent.webp",
      "/images/facilities-management/commercial-property-refurbishment-construction-company-kent.jpg",
      "/images/facilities-management/building-management-company-in-canterbury-kent-professional-maintanence.webp",
      "/images/facilities-management/Facilities-building-management-firm-in-Canterbury-Kent.webp",
    ],
    description: "Modern industrial-look office refurbishment in London, stripping out old party walls for open plan use with new flooring, rewire and LED lighting.",
    longDescription: "Our client requested an up to date modern approach for an office floor that had recently become available for new tenancy. They wanted to go with the industrial look which we supplied for them. Stripping out old party walls, for open plan use, new floor panels, rewire for equipment, data and building management, lagging and suspended led lighting.",
    tags: ["4 weeks", "Industrial Look", "Open Plan", "Commercial Fit Out", "LED Lighting"],
    serviceSlug: "facility-building-management",
    metaTitle: "Commercial Refurbishment in London | Superstructure Services",
    metaDescription: "Industrial-style office refurbishment in London. Open plan conversion, LED lighting, commercial fit-out by Superstructure Services.",
  },
  {
    slug: "kitchen-installation-in-canterbury-1",
    title: "Kitchen Installation in Canterbury",
    category: "Kitchen Installation",
    location: "Canterbury",
    image: "/images/Kitchen-Installation-in-Canterbury.jpg",
    images: [
      "/images/Kitchen-Installation-in-Canterbury.jpg",
      "/images/Kitchen-Installation-in-Canterbury-2.jpg",
      "/images/Kitchen-Installation-in-Canterbury-3.jpg",
      "/images/kitchen-installation/new-kitchen-installations-canterbury-kent.jpg",
      "/images/kitchen-installation/new-kitchen-installation-kent.jpg",
      "/images/kitchen-installation/kent-custom-kitchen-cabinets.jpg",
      "/images/kitchen-installation/kent-heritage-kitchen-restoration.jpg",
      "/images/kitchen-installation/kitchen-breakfast-bar-installation-canterbury.jpg",
    ],
    description: "Open plan kitchen diner extension in Canterbury with custom aluminium window and true handleless kitchen installation.",
    longDescription: "Our client in Canterbury required an open plan kitchen diner. So after planning permission was consented we extended the kitchen area and knocked through to a dining area. Once the custom made aluminium window was fitted and the true handle less kitchen installed they were extremely happy with the outcome.",
    tags: ["4 weeks", "Kitchen Extension", "Open Plan", "Aluminium Window", "Handleless Kitchen"],
    serviceSlug: "kitchen-installation-service",
    metaTitle: "Kitchen Installation in Canterbury | Superstructure Services",
    metaDescription: "Open plan kitchen diner extension in Canterbury. Custom aluminium window, handleless kitchen by Superstructure Services.",
  },
  {
    slug: "roofing-in-canterbury-1",
    title: "Roofing in Canterbury",
    category: "Roofing",
    location: "Canterbury",
    image: "/images/Professional-roofing-service-in-Canterbury-Kent.jpg",
    images: [
      "/images/Professional-roofing-service-in-Canterbury-Kent.jpg",
      "/images/roofing-canterbury-1/Professional roofing service in Canterbury Kent.JPG",
      "/images/roofing-canterbury-1/Roofing in Canterbury.JPG",
      "/images/roofing-canterbury-1/Roofing installation in Canterbury Kent.JPG",
      "/images/roofing-canterbury-1/Roofing service Canterbury Kent.JPG",
      "/images/roofing-canterbury-1/Roofing service in Canterbury Kent.JPG",
      "/images/roofing-canterbury-1/Roofing specialist in Canterbury.JPG",
      "/images/roofing-canterbury-1/Professional roofing service in Canterbury Kent adelphi.JPG",
      "/images/roofing-canterbury-1/Roofing service Canterbury Kent adelphi.JPG",
    ],
    description: "Complete roof replacement in Canterbury using traditional products for a long-lasting, aesthetically pleasing result.",
    longDescription: "Our clients roof in Canterbury was beyond economical repair and also wasn't very aesthetically pleasing to look at. The decision was made to replace in a more traditional product not only providing a long lasting water tight job but one that was much more easier on the eye.",
    tags: ["3 weeks", "Roof Replacement", "Traditional Products", "Water Tight", "Canterbury"],
    serviceSlug: "new-roof-installation-repairs",
    metaTitle: "Roofing in Canterbury | Superstructure Services",
    metaDescription: "Complete roof replacement in Canterbury using traditional products. Long-lasting, water-tight installation by Superstructure Services.",
  },
  {
    slug: "cinema-room-installation-canterbury",
    title: "Cinema Room Installation",
    category: "Cinema Rooms",
    location: "Canterbury",
    image: "/images/cinema-room/cinema-room-in-canterbury.jpg",
    images: [
      "/images/cinema-room/cinema-room-in-canterbury.jpg",
    ],
    description: "Bespoke cinema room installation in Canterbury, Kent.",
    longDescription: "Our team designs and installs bespoke home cinema rooms across Canterbury and Kent, handling everything from acoustic treatment and projector setup to seating and lighting control.",
    tags: ["Cinema Room", "Home Cinema", "Canterbury", "Kent", "AV Installation"],
    serviceSlug: "cinema-room-installation",
    metaTitle: "Cinema Room Installation in Canterbury | Superstructure Services",
    metaDescription: "Bespoke cinema room installation in Canterbury, Kent. Full AV setup, acoustic treatment and lighting by Superstructure Services.",
  },
  {
    slug: "air-source-heat-pump-installation-canterbury",
    title: "Air Source Heat Pump Installation",
    category: "Air Source Heat Pumps",
    location: "Canterbury",
    image: "/images/air-source-heat-pump/air-source-heat-pumps-installer-canterbury-kent.webp",
    images: [
      "/images/air-source-heat-pump/air-source-heat-pumps-installer-canterbury-kent.webp",
      "/images/air-source-heat-pump/air-source-heat-pumps-and-conditioning.webp",
      "/images/air-source-heat-pump/air-conditioning-installer-in-canterbury-kent.webp",
      "/images/air-source-heat-pump/air-source-heat-pump-installation-canterbury.webp",
    ],
    description: "MCS-accredited air source heat pump installation in Canterbury, Kent.",
    longDescription: "Our MCS-accredited team installs air source heat pumps across Canterbury and the wider Kent area. We handle everything from survey to commissioning, ensuring maximum efficiency and eligibility for Government grant support.",
    tags: ["Air Source Heat Pump", "MCS Accredited", "Canterbury", "Kent", "Renewable Energy"],
    serviceSlug: "air-source-heat-pump",
    metaTitle: "Air Source Heat Pump Installation in Canterbury | Superstructure Services",
    metaDescription: "MCS-accredited air source heat pump installation in Canterbury, Kent. Eco-friendly heating with Government grant support by Superstructure Services.",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}

export function getRelatedProjects(project: Project, count = 3): Project[] {
  return PROJECTS.filter(
    (p) => p.slug !== project.slug && p.category === project.category
  )
    .concat(PROJECTS.filter((p) => p.slug !== project.slug && p.category !== project.category))
    .slice(0, count);
}
